In [10]:
import sys
!{sys.executable} -m pip install python-dotenv

Collecting python-dotenv
  Downloading python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.2.2

  WARNING: The script dotenv.exe is installed in 'C:\Users\havagyan\AppData\Local\anaconda3\envs\tesing_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [12]:
import os
import json
import time
from typing import Optional

import pandas as pd
from tqdm.auto import tqdm
from google import genai

from dotenv import load_dotenv

In [18]:
load_dotenv()

api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise ValueError("GEMINI_API_KEY is not set")

client = genai.Client(api_key=api_key)

Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.

In [105]:
SYSTEM_PROMPT = """
You are a requirements-oriented classifier for agile user stories. Your task is to classify the semantic relation between two provided user stories (Story A and Story B).

Based only on the provided story texts, you must choose exactly one label from: DUPLICATE, CONFLICT, DEPENDS_ON, NONE.

### LABEL DEFINITIONS & EXCLUSIONS

DUPLICATE
- Definition: Story A and Story B express the same core requirement intent, user need, and expected user-visible outcome. 
- Rules: Use DUPLICATE if one story is simply a more specific version of the other or adds a minor qualifier to the same core action, as long as the underlying functional requirement is identical.
- EXCLUSION (Actor Mismatch): Do NOT use DUPLICATE if the actors are different.
- EXCLUSION (Distinct Mechanisms): Do NOT use DUPLICATE if the stories describe fundamentally different technical actions, integration methods, or delivery mechanisms, even if they target the exact same entity. 

CONFLICT
- Definition: Story A and Story B are materially incompatible as stated. They cannot both be logically implemented and satisfied at the same time (e.g. if they refer to the same distinct instance but require different functionalities).
- Rules: Applies to contradictory permissions, states, approval conditions, required behaviors, access control, or runtime condition.
- EXCLUSION: Do not use CONFLICT merely because stories address different use cases or represent alternate paths.
- EXCLUSION (Warnings/Confirmations): Do NOT use CONFLICT when one story allows an action and the other story merely adds a warning, confirmation, or validation step to that same action. These are complementary, not contradictory.

DEPENDS_ON
- Definition: One story provides a capability, authorization, configuration, resource, data availability, or prior state that the other story logically requires in order to be executed or accessed.
- Rules: Use DEPENDS_ON only for clear sequential workflows where the downstream action cannot be meaningfully performed unless the upstream capability, resource, or state already exists. (e.g., modifying, updating, or deleting an entity logically requires the capability to first create, provision, or acquire that entity).
         Use DEPENDS_ON if one actor's goal relies on the safety, storage, or availability of a system resource that is provisioned or maintained by a completely different actor's goal.
- EXCLUSION: Do not use DEPENDS_ON if there is no clear requirment between stories, if the relationship is merely logical precedent or if it is simply a desire not a requirement. Do not make assumptions outside of the scope of the stories provided.
- Direction: You must determine the direction. If Story B requires Story A to happen first, Story B depends on Story A.

NONE
- Definition: None of the above relations are sufficiently supported by the text alone.
- Rules: Use NONE for stories that are merely topically related, exist in the same feature area, or share keywords but lack a strict dependency, duplication, or conflict. Prefer NONE over speculative relation assignments.

### DECISION RULES
1. Grounding: Base the decision ONLY on the content of Story A and Story B. Do not infer unstated background assumptions.
2. Step-by-Step Logic: First, evaluate the actors to ensure they match or interact functionally. Second, evaluate the core actions. Third, check at first whether the stories have a CONFLICT relation, if not, check for DUPLICATE, and if not only then check DEPENDS_ON relationship using the rules above.
3. Output formatting: If the label is DEPENDS_ON, set "source_story" to the story that depends on the other, and "target_story" to the story it requires. For all other labels, set both direction fields to null.

### EXAMPLES

Example 1:
Story A: As a Customer, I want to add items to my digital shopping cart, so that I can purchase multiple books at once.
Story B: As a Customer, I want to change the quantity of an item already in my shopping cart, so that I can buy multiple copies of the same book.
Output:
{
  "reason": "Story B involves modifying the quantity of items already in a cart. Logically, a downstream modification action requires the upstream capability to acquire/add items first (Story A). Therefore, B requires A as a workflow prerequisite.",
  "relation_type": "DEPENDS_ON",
  "source_story": "B",
  "target_story": "A"
}

Example 2:
Story A: As a Store Manager, I want to view a daily sales report, so that I can track overall revenue.
Story B: As a Store Manager, I want to view a daily sales report filtered by book genre, so that I can see which categories perform best.
Output:
{
  "reason": "Both stories involve the exact same actor viewing the exact same core report. Story B is simply a slightly refined version (adding a filter qualifier) of the core requirement in Story A. One subsumes the other.",
  "relation_type": "DUPLICATE",
  "source_story": null,
  "target_story": null
}

Example 3:
Story A: As a Warehouse Worker, I want an alert when stock drops below 10 units, so I can reorder.
Story B: As a Customer, I want to see an 'Out of Stock' badge on unavailable books, so I don't try to buy them.
Output:
{
  "reason": "The actors represent completely distinct roles with different viewpoints (Internal Worker vs External Customer). While both relate to the topic of inventory, one is an internal backend alert and the other is an external UI badge. Neither logically requires the other to function.",
  "relation_type": "NONE",
  "source_story": null,
  "target_story": null
}

Example 4:
Story A: As a System Admin, I want user passwords to expire every 30 days, to ensure security.
Story B: As a System Admin, I want user passwords to never expire, to reduce support tickets.
Output:
{
  "reason": "The rules established in both stories are materially incompatible. The system cannot simultaneously force passwords to expire every 30 days and allow them to never expire.",
  "relation_type": "CONFLICT",
  "source_story": null,
  "target_story": null
}

### OUTPUT FORMAT
Return EXACTLY ONE valid JSON object. Do not include markdown formatting or outside text.
{
  "reason": "1-2 sentences grounded only in the text, evaluating actors and core actions.",
  "relation_type": "DUPLICATE|CONFLICT|DEPENDS_ON|NONE",
  "source_story": "A|B|null",
  "target_story": "A|B|null"
}
""".strip()

In [107]:
def classify_story_pair(
    story_a: str,
    story_b: str,
    story_a_id: Optional[str] = None,
    story_b_id: Optional[str] = None,
    model_name: str = 'gemini-3-pro-preview'
):
    user_prompt = f"""
Story A ID: {story_a_id}
Story A:
{story_a}

Story B ID: {story_b_id}
Story B:
{story_b}

Return only valid JSON.
""".strip()

    full_prompt = f"{SYSTEM_PROMPT}\n\n{user_prompt}"

    response = client.models.generate_content(
        model=model_name,
        contents=full_prompt,
    )

    raw_text = response.text.strip()

    try:
        parsed = json.loads(raw_text)
    except json.JSONDecodeError:
        import re
        match = re.search(r"\{.*\}", raw_text, re.DOTALL)
        if not match:
            raise ValueError(f"Could not parse JSON from model output:\n{raw_text}")
        parsed = json.loads(match.group(0))

    relation_type = parsed.get("relation_type", "").strip().upper()
    reason = parsed.get("reason", "").strip()

    allowed = {"DUPLICATE", "CONFLICT", "DEPENDS_ON", "NONE"}
    if relation_type not in allowed:
        raise ValueError(f"Invalid label returned: {relation_type}")

    return {
        "story_a_id": story_a_id,
        "story_b_id": story_b_id,
        "story_a": story_a,
        "story_b": story_b,
        "relation_type": relation_type,
        "reason": reason,
        "raw_response": raw_text,
    }

In [109]:
def classify_row(row):
    result = classify_story_pair(
        story_a=row["story_1_text"],
        story_b=row["story_2_text"],
        story_a_id=row["pair_id_1"],
        story_b_id=row["pair_id_2"],
        model_name="gemini-3-pro-preview"
    )
    return pd.Series({
        "predicted_relation": result["relation_type"],
        "llm_reason": result["reason"],
        "raw_response": result.get("raw_response", "")
    })

In [119]:
# UPLOAD THE PREPROCESSED DATASET
candidate_pairs_final = pd.read_csv(r'pred_res\neo4j\g14_inter_story_for_llm.csv')
candidate_pairs_final

,pair_id_1,pair_id_2,transformation,story_1_text,story_2_text,predicted_relation,llm_reason,response_time_sec,true_label,data_source,raw_response,source_story,target_story
0,0,1,NaN,"As a Publisher, I want to publish a dataset, s...","As a Publisher, I want to publish a dataset, s...",CONFLICT,Both stories describe the act of publishing a ...,0.839088,CONFLICT,natural,"{\n ""relation_type"": ""CONFLICT"",\n ""source_s...",NaN,NaN
1,0,21,NaN,"As a Publisher, I want to publish a dataset, s...","As a Consumer, I want to view a data package o...",NONE,The stories involve different actors (Publishe...,0.720764,NONE,natural,"{\n ""relation_type"": ""NONE"",\n ""source_story...",NaN,NaN
2,0,22,NaN,"As a Publisher, I want to publish a dataset, s...","As a publisher, I want to show the world how m...",CONFLICT,Story A describes a requirement for restricted...,1.137041,NONE,natural,"{\n ""relation_type"": ""NONE"",\n ""source_story...",NaN,NaN
3,0,46,NaN,"As a Publisher, I want to publish a dataset, s...","As a Consumer, I want to view a Datapackage at...",NONE,The actors are different (Publisher vs. Consum...,0.968363,NONE,natural,"{\n ""relation_type"": ""NONE"",\n ""source_story...",NaN,NaN
4,0,58,NaN,"As a Publisher, I want to publish a dataset, s...","As an owner, I want to view all the people in ...",NONE,The stories involve different actors (Publishe...,0.706517,NONE,natural,"{\n ""relation_type"": ""NONE"",\n ""source_story...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,59,60,NaN,"As an owner, I want to make a user an owner, s...","As an owner, I want to remove a user as an own...",NONE,Story A and Story B describe opposite administ...,0.652525,NONE,natural,"{\n ""relation_type"": ""NONE"",\n ""source_story...",NaN,NaN
67,59,63,NaN,"As an owner, I want to make a user an owner, s...","As an Admin, I want to have a pricing plan and...",NONE,The stories involve different actors (Owner vs...,0.791965,NONE,natural,"{\n ""relation_type"": ""NONE"",\n ""source_story...",NaN,NaN
68,63,64,NaN,"As an Admin, I want to have a pricing plan and...","As a Publisher, I want to know if this site ha...",NONE,The stories involve different actors (Admin vs...,0.789064,DEPENDS_ON,natural,"{\n ""relation_type"": ""NONE"",\n ""source_story...",NaN,NaN
69,63,65,NaN,"As an Admin, I want to have a pricing plan and...","As a Publisher, I want to sign up for a given ...",DEPENDS_ON,Story B describes a publisher signing up for a...,0.821794,DEPENDS_ON,natural,"{\n ""relation_type"": ""DEPENDS_ON"",\n ""source...",B,A
70,64,65,NaN,"As a Publisher, I want to know if this site ha...","As a Publisher, I want to sign up for a given ...",DEPENDS_ON,Story B involves signing up for a specific pri...,0.705510,DEPENDS_ON,natural,"{\n ""relation_type"": ""DEPENDS_ON"",\n ""source...",B,A

In [121]:
test_df = candidate_pairs_final.head(3).copy()
test_preds = test_df.apply(classify_row, axis=1)
test_result = pd.concat([test_df, test_preds], axis=1)
test_result

,pair_id_1,pair_id_2,transformation,story_1_text,story_2_text,predicted_relation,llm_reason,response_time_sec,true_label,data_source,raw_response,source_story,target_story,predicted_relation,llm_reason,raw_response
0,0,1,NaN,"As a Publisher, I want to publish a dataset, s...","As a Publisher, I want to publish a dataset, s...",CONFLICT,Both stories describe the act of publishing a ...,0.839088,CONFLICT,natural,"{\n ""relation_type"": ""CONFLICT"",\n ""source_s...",NaN,NaN,NONE,Both stories involve the same actor publishing...,"{\n ""reason"": ""Both stories involve the same ..."
1,0,21,NaN,"As a Publisher, I want to publish a dataset, s...","As a Consumer, I want to view a data package o...",NONE,The stories involve different actors (Publishe...,0.720764,NONE,natural,"{\n ""relation_type"": ""NONE"",\n ""source_story...",NaN,NaN,DEPENDS_ON,Story B involves a Consumer viewing a dataset ...,"{\n ""reason"": ""Story B involves a Consumer vi..."
2,0,22,NaN,"As a Publisher, I want to publish a dataset, s...","As a publisher, I want to show the world how m...",CONFLICT,Story A describes a requirement for restricted...,1.137041,NONE,natural,"{\n ""relation_type"": ""NONE"",\n ""source_story...",NaN,NaN,DEPENDS_ON,Story B involves showing 'published data' to t...,"{\n ""reason"": ""Story B involves showing 'publ..."

In [122]:
def run_cross_story_experiment(
    df,
    n_rows=None,
    model_name="gemini-3-pro-preview",
    save_every=None
):
    """
    Run cross-story classification on the first n_rows of df.
    
    Parameters
    ----------
    df : pandas.DataFrame
        Must contain:
        - pair_id_1
        - pair_id_2
        - story_1_text
        - story_2_text
    n_rows : int or None
        If set, only run on the first n_rows rows.
        If None, run on the full dataframe.
    model_name : str
        Gemini model name.
    save_every : int or None
        If set, saves intermediate CSV every N rows.
    """
    
    if n_rows is not None:
        run_df = df.head(n_rows).copy().reset_index(drop=True)
    else:
        run_df = df.copy().reset_index(drop=True)

    results = []
    run_start = time.perf_counter()

    for idx, row in tqdm(run_df.iterrows(), total=len(run_df), desc=f"Running {len(run_df)} pairs"):
        row_start = time.perf_counter()
        # print('a', row["story_1_text"])
        # print('b',row["story_2_text"])
        # print('c', row["pair_id_1"])
        # print('d', row["pair_id_2"])
        try:
            result = classify_story_pair(
                story_a=row["story_1_text"],
                story_b=row["story_2_text"],
                story_a_id=row["pair_id_1"],
                story_b_id=row["pair_id_2"],
                model_name=model_name
            )

            row_end = time.perf_counter()
            row_seconds = row_end - row_start

            results.append({
                "row_index": idx,
                "pair_id_1": row["pair_id_1"],
                "pair_id_2": row["pair_id_2"],
                "candidate_source": row.get("candidate_source", None),
                "score": row.get("score", None),
                "predicted_relation": result.get("relation_type", None),
                "llm_reason": result.get("reason", None),
                "raw_response": result.get("raw_response", None),
                "response_time_sec": row_seconds
            })

            print(
                f"Row {idx} done | pair ({row['pair_id_1']}, {row['pair_id_2']}) "
                f"| label={result.get('relation_type', 'NA')} "
                f"| time={row_seconds:.2f}s"
            )

        except Exception as e:
            row_end = time.perf_counter()
            row_seconds = row_end - row_start

            results.append({
                "row_index": idx,
                "pair_id_1": row["pair_id_1"],
                "pair_id_2": row["pair_id_2"],
                "candidate_source": row.get("candidate_source", None),
                "score": row.get("score", None),
                "predicted_relation": "ERROR",
                "llm_reason": str(e),
                "raw_response": None,
                "response_time_sec": row_seconds
            })

            print(
                f"Row {idx} ERROR | pair ({row['pair_id_1']}, {row['pair_id_2']}) "
                f"| time={row_seconds:.2f}s | error={e}"
            )

        if save_every is not None and (idx + 1) % save_every == 0:
            temp_df = pd.DataFrame(results)
            temp_df.to_csv(f"temp_results_{idx+1}_rows.csv", index=False)

    run_end = time.perf_counter()
    total_seconds = run_end - run_start

    results_df = pd.DataFrame(results)

    summary = {
        "n_rows": len(run_df),
        "total_time_sec": total_seconds,
        "avg_time_per_row_sec": results_df["response_time_sec"].mean() if len(results_df) > 0 else None,
        "min_time_sec": results_df["response_time_sec"].min() if len(results_df) > 0 else None,
        "max_time_sec": results_df["response_time_sec"].max() if len(results_df) > 0 else None,
    }

    print("\n===== RUN SUMMARY =====")
    print(f"Rows processed: {summary['n_rows']}")
    print(f"Total time: {summary['total_time_sec']:.2f} sec")
    print(f"Average / row: {summary['avg_time_per_row_sec']:.2f} sec")
    print(f"Min row time: {summary['min_time_sec']:.2f} sec")
    print(f"Max row time: {summary['max_time_sec']:.2f} sec")

    return results_df, summary

In [59]:
# results_3, summary_3 = run_cross_story_experiment(candidate_pairs_final, n_rows=3, model_name="gemini-3-pro-preview")
# results_5, summary_5 = run_cross_story_experiment(candidate_pairs_final, n_rows=5, model_name="gemini-3-pro-preview")
# results_7, summary_7 = run_cross_story_experiment(candidate_pairs_final, n_rows=7, model_name="gemini-3-pro-preview")

In [125]:
results_full, summary_full = run_cross_story_experiment(candidate_pairs_final, n_rows=None, model_name="gemini-3.1-flash-lite-preview")

Running 71 pairs:   0%|          | 0/71 [00:00<?, ?it/s]

Row 0 done | pair (0, 1) | label=CONFLICT | time=1.24s
Row 1 done | pair (0, 21) | label=NONE | time=0.82s
Row 2 done | pair (0, 22) | label=CONFLICT | time=0.81s
Row 3 done | pair (0, 46) | label=NONE | time=0.96s
Row 4 done | pair (0, 58) | label=NONE | time=0.88s
Row 5 done | pair (1, 21) | label=DEPENDS_ON | time=0.96s
Row 6 done | pair (1, 22) | label=NONE | time=0.88s
Row 7 done | pair (1, 24) | label=DEPENDS_ON | time=0.81s
Row 8 done | pair (2, 8) | label=DEPENDS_ON | time=1.02s
Row 9 done | pair (2, 11) | label=NONE | time=1.03s
Row 10 done | pair (2, 39) | label=DEPENDS_ON | time=0.99s
Row 11 done | pair (2, 51) | label=NONE | time=0.84s
Row 12 done | pair (2, 63) | label=NONE | time=0.82s
Row 13 done | pair (2, 65) | label=DUPLICATE | time=1.02s
Row 14 done | pair (8, 11) | label=DEPENDS_ON | time=0.75s
Row 15 done | pair (8, 39) | label=NONE | time=0.84s
Row 16 done | pair (9, 18) | label=DEPENDS_ON | time=0.91s
Row 17 done | pair (9, 19) | label=NONE | time=0.96s
Row 18 done | pair (9, 40) | label=NONE | time=1.02s
Row 19 done | pair (9, 41) | label=NONE | time=0.90s
Row 20 done | pair (9, 57) | label=NONE | time=0.95s
Row 21 done | pair (9, 60) | label=NONE | time=0.68s
Row 22 done | pair (11, 13) | label=NONE | time=0.95s
Row 23 done | pair (11, 39) | label=NONE | time=0.91s
Row 24 done | pair (11, 65) | label=NONE | time=0.93s
Row 25 done | pair (13, 21) | label=NONE | time=1.22s
Row 26 done | pair (13, 24) | label=NONE | time=1.02s
Row 27 done | pair (13, 40) | label=DEPENDS_ON | time=0.92s
Row 28 done | pair (18, 19) | label=DUPLICATE | time=0.81s
Row 29 done | pair (18, 20) | label=NONE | time=0.92s
Row 30 done | pair (18, 41) | label=NONE | time=0.82s
Row 31 done | pair (20, 24) | label=DUPLICATE | time=0.91s
Row 32 done | pair (20, 39) | label=NONE | time=0.82s
Row 33 done | pair (20, 41) | label=NONE | time=0.82s
Row 34 done | pair (20, 46) | label=NONE | time=1.03s
Row 35 done | pair (21, 27) | label=DUPLICATE | time=0.91s
Row 36 done | pair (21, 29) | label=NONE | time=0.82s
Row 37 done | pair (21, 44) | label=NONE | time=0.84s
Row 38 done | pair (21, 46) | label=DUPLICATE | time=0.79s
Row 39 done | pair (22, 51) | label=NONE | time=0.92s
Row 40 done | pair (22, 52) | label=NONE | time=1.76s
Row 41 done | pair (24, 39) | label=NONE | time=0.90s
Row 42 done | pair (24, 41) | label=DEPENDS_ON | time=0.81s
Row 43 done | pair (24, 46) | label=NONE | time=0.92s
Row 44 done | pair (27, 29) | label=NONE | time=1.02s
Row 45 done | pair (27, 51) | label=NONE | time=1.02s
Row 46 done | pair (27, 52) | label=NONE | time=1.23s
Row 47 done | pair (27, 64) | label=NONE | time=1.00s
Row 48 done | pair (29, 40) | label=NONE | time=1.44s
Row 49 done | pair (39, 40) | label=NONE | time=1.43s
Row 50 done | pair (39, 41) | label=DEPENDS_ON | time=1.12s
Row 51 done | pair (40, 41) | label=NONE | time=1.12s
Row 52 done | pair (44, 47) | label=NONE | time=0.92s
Row 53 done | pair (46, 47) | label=NONE | time=0.92s
Row 54 done | pair (46, 52) | label=NONE | time=0.79s
Row 55 done | pair (47, 52) | label=NONE | time=1.05s
Row 56 done | pair (51, 52) | label=DUPLICATE | time=0.92s
Row 57 done | pair (51, 58) | label=NONE | time=0.92s
Row 58 done | pair (51, 64) | label=NONE | time=0.87s
Row 59 done | pair (52, 58) | label=NONE | time=0.77s
Row 60 done | pair (57, 58) | label=DEPENDS_ON | time=1.84s
Row 61 done | pair (57, 59) | label=NONE | time=1.13s
Row 62 done | pair (57, 60) | label=NONE | time=1.12s
Row 63 done | pair (58, 59) | label=DEPENDS_ON | time=1.02s
Row 64 done | pair (58, 60) | label=DUPLICATE | time=0.84s
Row 65 done | pair (58, 64) | label=NONE | time=0.79s
Row 66 done | pair (59, 60) | label=NONE | time=0.82s
Row 67 done | pair (59, 63) | label=NONE | time=0.81s
Row 68 done | pair (63, 64) | label=NONE | time=0.77s
Row 69 done | pair (63, 65) | label=DEPENDS_ON | time=0.86s
Row 70 done | pair (64, 65) | label=DEPENDS_ON | time=0.82s

===== RUN SUMMARY =====
Rows processed: 71
Total time: 68.45 sec
Average / row: 0.96 sec
Min row time: 0.68 sec
Max row time: 1.84 sec

In [31]:
# timing_comparison = pd.DataFrame([
#     summary_3,
#     summary_5,
#     summary_7,
#     summary_full
# ])

# timing_comparison

In [127]:
results_full[results_full['predicted_relation']!='NONE']['predicted_relation'].value_counts()

predicted_relation
DEPENDS_ON    13
DUPLICATE      7
CONFLICT       2
Name: count, dtype: int64

In [62]:
results_full[results_full['predicted_relation']!='NONE']['predicted_relation'].value_counts()

predicted_relation
DEPENDS_ON    46
DUPLICATE     23
CONFLICT       4
Name: count, dtype: int64

In [33]:
results_full

,row_index,pair_id_1,pair_id_2,candidate_source,score,predicted_relation,llm_reason,raw_response,response_time_sec
0,0,3,3,None,None,DUPLICATE,Both stories describe the exact same actor (Vi...,"{\n ""reason"": ""Both stories describe the exac...",1.054808
1,1,3,3,None,None,CONFLICT,Story A and Story B describe diametrically opp...,"{\n ""reason"": ""Story A and Story B describe d...",0.967175
2,2,3,3,None,None,NONE,"The stories describe different, mutually exclu...","{\n ""reason"": ""The stories describe different...",1.458665
3,3,3,3,None,None,DEPENDS_ON,The stories describe the same feature from dif...,"{\n ""reason"": ""The stories describe the same ...",0.990334
4,4,4,4,None,None,DUPLICATE,"Both stories describe the same actor, intent, ...","{\n ""reason"": ""Both stories describe the same...",1.038012
...,...,...,...,...,...,...,...,...,...
111,111,16,16,None,None,DUPLICATE,Both stories describe the act of publishing a ...,"{\n ""reason"": ""Both stories describe the act ...",0.965389
112,112,63,63,None,None,DUPLICATE,Both stories involve the same actor and the sa...,"{\n ""reason"": ""Both stories involve the same ...",0.846886
113,113,19,19,None,None,CONFLICT,Story A requires that undeleting a data packag...,"{\n ""reason"": ""Story A requires that undeleti...",1.180195
114,114,22,22,None,None,NONE,Story A and Story B represent fundamentally di...,"{\n ""reason"": ""Story A and Story B represent ...",0.919954
115,115,0,0,None,None,CONFLICT,Both stories describe the same actor and core ...,"{\n ""reason"": ""Both stories describe the same...",0.964402

In [23]:
df2 = candidate_pairs_final.merge(
    results_full[
        ["pair_id_1", "pair_id_2", "predicted_relation", "llm_reason", "raw_response", "response_time_sec"]
    ],
    on=["pair_id_1", "pair_id_2"],
    how="left"
)

In [91]:
df_tmp1 = df2[df2['predicted_relation'] != 'NONE']
for i, row in df_tmp1.iterrows():
    print(f"Index: {i}")
    print(f"Predicted relation: {row['predicted_relation']}")
    print(f"Story id: {row['pair_id_1']} ")
    print(row["story_1_text"])
    print()
    print(f"Story id: {row['pair_id_2']} ")
    print(row["story_2_text"])
    print()
    print("LLM reason:")
    print(row["llm_reason"])
    print("\n" + "=" * 80 + "\n")

Index: 0
Predicted relation: CONFLICT
Story id: 0
As a Publisher, I want to publish a dataset, so that I can view just the dataset with a few people.

Story id: 1
As a Publisher, I want to publish a dataset, so that I can share the dataset publicly with everyone.

LLM reason:
Both stories involve the same actor performing the same core action of publishing a dataset, but they define mutually exclusive access levels (restricted sharing vs. public sharing). Because the system cannot simultaneously restrict access to a few people and make the dataset available to everyone, these requirements are in conflict.

================================================================================

Index: 1
Predicted relation: DEPENDS_ON
Story id: 0
As a Publisher, I want to publish a dataset, so that I can view just the dataset with a few people.

Story id: 7
As a Publisher, I want to configure my client, so that I can start publishing data packages.

LLM reason:
Publishing a dataset (Story A) requires the prerequisite configuration of the client (Story B) to establish the connection and capability to transmit data packages. Therefore, the ability to perform the action in A is logically dependent on the configuration completed in B.

================================================================================

Index: 2
Predicted relation: DUPLICATE
Story id: 0
As a Publisher, I want to publish a dataset, so that I can view just the dataset with a few people.

Story id: 16
As a Publisher, I want to publish a data package in the UI, so that that it is available and published.

LLM reason:
Story A and Story B describe the same actor (Publisher) performing the same core action (publishing data) to achieve a similar outcome (making data available/accessible). Story B is a more specific description regarding the UI mechanism, but they share the same functional intent.

================================================================================

Index: 3
Predicted relation: DUPLICATE
Story id: 0
As a Publisher, I want to publish a dataset, so that I can view just the dataset with a few people.

Story id: 17
As a Publisher, I want to create a data package in the UI so that it is available and published.

LLM reason:
Both stories describe the act of publishing or making a dataset/package available to others as a Publisher. The requirement to publish a dataset (Story 0) and the requirement to create a data package in the UI to make it published (Story 17) represent the same core functional intent of making content public, despite minor variations in terminology.

================================================================================

Index: 5
Predicted relation: CONFLICT
Story id: 0
As a Publisher, I want to publish a dataset, so that I can view just the dataset with a few people.

Story id: 22
As a publisher, I want to show the world how my published data is, so that that it immediately catches consumer's attention.

LLM reason:
The two stories describe distinct and incompatible accessibility intents: Story A limits visibility to 'a few people' (private/restricted), whereas Story B requires the data to be shown to 'the world' (public). These requirements are materially incompatible regarding the access state of the published dataset.

================================================================================

Index: 9
Predicted relation: DUPLICATE
Story id: 0
As a Publisher, I want to publish a dataset, so that I can view just the dataset with a few people.

Story id: 66
As a Publisher, I want to have private data packages, so that I can share just with my team.

LLM reason:
Both stories describe the same actor (Publisher) aiming to restrict access to data (view with a few people vs. share just with my team). These are functionally equivalent requirements for private data sharing.

================================================================================

Index: 11
Predicted relation: DEPENDS_ON
Story id: 1
As a Publisher, I want to publish a dataset, so that I can share the dataset publicly with everyone.

Story id: 7
As a Publisher, I want to configure my client, so that I can start publishing data packages.

LLM reason:
Publishing a dataset (Story 1) requires the prior capability to configure the client interface (Story 7) to enable the publication process. Therefore, the execution of Story 1 depends on the technical configuration established in Story 7.

================================================================================

Index: 12
Predicted relation: DUPLICATE
Story id: 1
As a Publisher, I want to publish a dataset, so that I can share the dataset publicly with everyone.

Story id: 16
As a Publisher, I want to publish a data package in the UI, so that that it is available and published.

LLM reason:
Both stories describe the same actor (Publisher) performing the same core action (publishing a dataset/package to make it publicly available). Story B specifies the delivery mechanism (UI), but the underlying functional requirement and expected outcome are identical to Story A.

================================================================================

Index: 13
Predicted relation: DUPLICATE
Story id: 1
As a Publisher, I want to publish a dataset, so that I can share the dataset publicly with everyone.

Story id: 17
As a Publisher, I want to create a data package in the UI so that it is available and published.

LLM reason:
Both stories describe the same actor (Publisher) aiming to make a dataset publicly available. 'Creating a data package' and 'publishing a dataset' represent the same core intent and functional requirement in this context.

================================================================================

Index: 14
Predicted relation: DEPENDS_ON
Story id: 1
As a Publisher, I want to publish a dataset, so that I can share the dataset publicly with everyone.

Story id: 21
As a Consumer, I want to view a data package online, so that I can get a sense of whether this is the dataset I want.

LLM reason:
Story B involves viewing a dataset to assess its relevance, which presupposes the existence and availability of the published dataset described in Story A. Without the publishing action, there is no dataset for the consumer to view.

================================================================================

Index: 15
Predicted relation: DUPLICATE
Story id: 1
As a Publisher, I want to publish a dataset, so that I can share the dataset publicly with everyone.

Story id: 22
As a publisher, I want to show the world how my published data is, so that that it immediately catches consumer's attention.

LLM reason:
Both stories involve the same actor (Publisher) and the same core action (publishing a dataset for public viewing). Story B is a subjective, qualitative rephrasing of the functional requirement established in Story A, making them duplicative in intent.

================================================================================

Index: 16
Predicted relation: DEPENDS_ON
Story id: 1
As a Publisher, I want to publish a dataset, so that I can share the dataset publicly with everyone.

Story id: 23
As a consumer, I want to view the data package, so that that I can get a sense of whether I want this dataset or not.

LLM reason:
The stories involve different actors (Publisher vs. Consumer) performing distinct actions (publishing vs. viewing). While they both relate to the same data, the act of viewing logically depends on the existence of the published dataset; therefore, the consumer cannot view the package unless it has been published by the publisher.

================================================================================

Index: 17
Predicted relation: DEPENDS_ON
Story id: 1
As a Publisher, I want to publish a dataset, so that I can share the dataset publicly with everyone.

Story id: 24
As a Publisher, I want to preview a datapackage I have prepared, so that that I can check it works and share the results.

LLM reason:
Story B represents a validation and verification step that occurs during the preparation of a dataset, whereas Story A represents the final act of making the dataset public. Publishing the dataset in Story A logically depends on the prior verification or previewing process described in Story B to ensure the data is prepared correctly.

================================================================================

Index: 20
Predicted relation: DEPENDS_ON
Story id: 2
As a Publisher, I want to sign up for an account, so that that I can publish my data package to the registry and to have a publisher account to publish my data package under.

Story id: 4
As a Publisher, I want to know what do next after signing up, so that that I can get going quickly.

LLM reason:
Story B describes an onboarding or guidance requirement that logically follows the successful completion of the account registration process described in Story A.

================================================================================

Index: 22
Predicted relation: DEPENDS_ON
Story id: 2
As a Publisher, I want to sign up for an account, so that that I can publish my data package to the registry and to have a publisher account to publish my data package under.

Story id: 6
As a Publisher, I want to import my data package into the registry, so that my data has a permanent online home to access.

LLM reason:
Importing a data package into the registry (Story B) logically requires the existence of a publisher account and the associated identity/permissions (Story A) to successfully associate the data package with the publisher. Therefore, the import action depends on the prior registration step.

================================================================================

Index: 23
Predicted relation: DEPENDS_ON
Story id: 2
As a Publisher, I want to sign up for an account, so that that I can publish my data package to the registry and to have a publisher account to publish my data package under.

Story id: 7
As a Publisher, I want to configure my client, so that I can start publishing data packages.

LLM reason:
Story B involves configuring a client to perform the act of publishing, which logically requires the user to first possess a valid publisher account as established in Story A.

================================================================================

Index: 24
Predicted relation: DEPENDS_ON
Story id: 2
As a Publisher, I want to sign up for an account, so that that I can publish my data package to the registry and to have a publisher account to publish my data package under.

Story id: 8
As a Publisher, I want to use a publish command to update a data package that is already in the registry, so that it appears there.

LLM reason:
Updating an existing data package in the registry (Story B) logically requires that the data package has been previously created/published and that the user possesses a valid publisher account (Story A). Therefore, the ability to update an entity depends on the prerequisite existence of that entity and the associated account.

================================================================================

Index: 25
Predicted relation: DEPENDS_ON
Story id: 2
As a Publisher, I want to sign up for an account, so that that I can publish my data package to the registry and to have a publisher account to publish my data package under.

Story id: 10
As a Publisher, I want to permanently delete a data package, so that that it no longer takes up storage space.

LLM reason:
The ability to delete a data package (Story B) logically requires that the publisher has an account and has already successfully published data packages to the registry (Story A). Therefore, Story B is a downstream workflow dependency on the existence of the publisher account and the data publication capability established in Story A.

================================================================================

Index: 27
Predicted relation: DEPENDS_ON
Story id: 2
As a Publisher, I want to sign up for an account, so that that I can publish my data package to the registry and to have a publisher account to publish my data package under.

Story id: 12
As a Publisher, I want to data to be validated when I publish it, so that that I know immediately if I have accidentally broken my data or have bugs and can take action to correct.

LLM reason:
Story B describes the validation of data during the publishing process, which presupposes the ability to publish data. Since the actor must first establish a publisher account (Story A) to perform the action of publishing (Story B), the latter depends on the account creation capability.

================================================================================

Index: 28
Predicted relation: DEPENDS_ON
Story id: 2
As a Publisher, I want to sign up for an account, so that that I can publish my data package to the registry and to have a publisher account to publish my data package under.

Story id: 14
As a Publisher, I want to publish a data package where its resource data is stored on my servers but the registry caches a copy of that data, so that that if my data is lost or gets broken I still have a copy people can use.

LLM reason:
Story B involves the action of publishing a data package, which logically requires the actor to already possess a publisher account and registry registration as defined in Story A.

================================================================================

Index: 29
Predicted relation: DEPENDS_ON
Story id: 2
As a Publisher, I want to sign up for an account, so that that I can publish my data package to the registry and to have a publisher account to publish my data package under.

Story id: 16
As a Publisher, I want to publish a data package in the UI, so that that it is available and published.

LLM reason:
Story B involves publishing a data package, which requires the publisher to first possess an active account and registry identity, as outlined in the signup requirement of Story A. Therefore, the publishing action is logically dependent on the successful completion of the account creation process.

================================================================================

Index: 30
Predicted relation: DEPENDS_ON
Story id: 2
As a Publisher, I want to sign up for an account, so that that I can publish my data package to the registry and to have a publisher account to publish my data package under.

Story id: 17
As a Publisher, I want to create a data package in the UI so that it is available and published.

LLM reason:
Story B involves publishing a data package, which requires an existing account and publisher profile as a prerequisite. Since Story A provides the capability to sign up and establish this publisher account, Story B is logically dependent on the successful execution of Story A.

================================================================================

Index: 31
Predicted relation: DEPENDS_ON
Story id: 2
As a Publisher, I want to sign up for an account, so that that I can publish my data package to the registry and to have a publisher account to publish my data package under.

Story id: 39
As a Publisher, I want to tag datapackage to create a snapshot of data on the registry server, so that that consumers can refer to it.

LLM reason:
Story B involves performing an action (tagging a datapackage) that assumes the Publisher already has an account and has published data on the registry. The capability to publish and manage data packages (Story A) is a prerequisite for tagging those specific packages (Story B).

================================================================================

Index: 33
Predicted relation: DEPENDS_ON
Story id: 2
As a Publisher, I want to sign up for an account, so that that I can publish my data package to the registry and to have a publisher account to publish my data package under.

Story id: 55
As an Owner, I want to invite an existing user, so that the user can become a member of my publisher.

LLM reason:
Story B requires the existence of a 'publisher' account and members to be invited to it, while Story A provides the capability to create such a publisher account. Therefore, the ability to invite members to a publisher (B) logically depends on the existence of that publisher account (A).

================================================================================

Index: 34
Predicted relation: DEPENDS_ON
Story id: 2
As a Publisher, I want to sign up for an account, so that that I can publish my data package to the registry and to have a publisher account to publish my data package under.

Story id: 56
As an owner, I want to invite someone using their email to sign up and become a member of my Publisher, so that that they are authorized to publish data packages under my Publisher.

LLM reason:
Story B involves inviting a new member to a Publisher account, which logically assumes the existence of that Publisher account and the ability to register one. Therefore, the invitation and membership management in B depend on the account creation capability defined in A.

================================================================================

Index: 36
Predicted relation: DEPENDS_ON
Story id: 2
As a Publisher, I want to sign up for an account, so that that I can publish my data package to the registry and to have a publisher account to publish my data package under.

Story id: 65
As a Publisher, I want to sign up for a given pricing plan, so that that I am entitled to what it allows.

LLM reason:
Story B involves selecting a specific pricing plan during signup, which logically requires the foundational capability of creating a publisher account (Story A) to exist first. Without the account creation process, the publisher cannot be entitled to or sign up for a plan.

================================================================================

Index: 51
Predicted relation: DEPENDS_ON
Story id: 4
As a Publisher, I want to know what do next after signing up, so that that I can get going quickly.

Story id: 65
As a Publisher, I want to sign up for a given pricing plan, so that that I am entitled to what it allows.

LLM reason:
Story A describes a post-signup onboarding requirement, whereas Story B describes the initial act of signing up for a plan. Logically, the process of signing up (Story B) must occur before a user can move to the next steps of onboarding (Story A).

================================================================================

Index: 59
Predicted relation: DEPENDS_ON
Story id: 6
As a Publisher, I want to import my data package into the registry, so that my data has a permanent online home to access.

Story id: 8
As a Publisher, I want to use a publish command to update a data package that is already in the registry, so that it appears there.

LLM reason:
Story B involves updating a data package that is already in the registry. Logically, modifying or updating an existing entity requires the prerequisite capability to initially import or create that entity in the registry, as described in Story A.

================================================================================

Index: 60
Predicted relation: DEPENDS_ON
Story id: 6
As a Publisher, I want to import my data package into the registry, so that my data has a permanent online home to access.

Story id: 11
As a Publisher, I want to validate the data I am about to publish to the registry, so that that I publish good data and know that I am doing.

LLM reason:
Validating the data (Story B) is a preparatory step that must occur before or during the process of importing it into the registry (Story A). The import action logically requires that the data has been checked for quality/correctness first.

================================================================================

Index: 61
Predicted relation: DUPLICATE
Story id: 6

### SAVING

In [79]:
temp_df = pd.DataFrame(df2)
temp_df.to_csv(f"pred_res\g14-datahub_FINAL_PROMPT_transformations_new2.csv", index=False)

<>:2: SyntaxWarning: invalid escape sequence '\g'
<>:2: SyntaxWarning: invalid escape sequence '\g'
C:\Users\havagyan\AppData\Local\Temp\ipykernel_19464\766154093.py:2: SyntaxWarning: invalid escape sequence '\g'
  temp_df.to_csv(f"pred_res\g14-datahub_FINAL_PROMPT_transformations_new2.csv", index=False)

In [131]:
results_full.to_csv(r"pred_res\neo4j\g14_inter_story_for_llm_predicted.csv", index=False)

In [85]:
results_full

,row_index,pair_id_1,pair_id_2,candidate_source,score,predicted_relation,llm_reason,raw_response,response_time_sec
0,0,3,3,None,None,CONFLICT,The stories describe fundamentally incompatibl...,"{\n ""reason"": ""The stories describe fundament...",1.036399
1,1,4,4,None,None,CONFLICT,Story A expresses a user requirement for guida...,"{\n ""reason"": ""Story A expresses a user requi...",0.864188
2,2,5,5,None,None,CONFLICT,Story A defines an action (inviting a user) th...,"{\n ""reason"": ""Story A defines an action (inv...",0.876515
3,3,25,25,None,None,CONFLICT,The stories involve different actors (Consumer...,"{\n ""reason"": ""The stories involve different ...",0.796284
4,4,26,26,None,None,CONFLICT,Story A and Story B describe contradictory acc...,"{\n ""reason"": ""Story A and Story B describe c...",0.904144
5,5,30,30,None,None,CONFLICT,Story A defines a requirement for a Consumer t...,"{\n ""reason"": ""Story A defines a requirement ...",0.787136
6,6,31,31,None,None,CONFLICT,Story A seeks to enable the use of a data pack...,"{\n ""reason"": ""Story A seeks to enable the us...",0.891374
7,7,32,32,None,None,CONFLICT,Story A defines a capability for a Consumer to...,"{\n ""reason"": ""Story A defines a capability f...",0.894879
8,8,35,35,None,None,CONFLICT,The stories describe materially incompatible p...,"{\n ""reason"": ""The stories describe materiall...",1.004755
9,9,36,36,None,None,CONFLICT,Story A describes a desired functional capabil...,"{\n ""reason"": ""Story A describes a desired fu...",0.723666
10,10,37,37,None,None,CONFLICT,Story A seeks to enable the installation of mu...,"{\n ""reason"": ""Story A seeks to enable the in...",0.890048
11,11,38,38,None,None,CONFLICT,Story A describes a Developer's requirement to...,"{\n ""reason"": ""Story A describes a Developer'...",0.722298
12,12,43,43,None,None,CONFLICT,The stories are materially incompatible as the...,"{\n ""reason"": ""The stories are materially inc...",0.773424
13,13,45,45,None,None,CONFLICT,The stories describe materially incompatible r...,"{\n ""reason"": ""The stories describe materiall...",0.687565
14,14,49,49,None,None,CONFLICT,Story A describes a desire for consumers to ac...,"{\n ""reason"": ""Story A describes a desire for...",0.899216
15,15,54,54,None,None,CONFLICT,Story A provides a capability for Owners to ed...,"{\n ""reason"": ""Story A provides a capability ...",0.712773
16,16,56,56,None,None,CONFLICT,Story A defines a feature for owners to invite...,"{\n ""reason"": ""Story A defines a feature for ...",0.828616
17,17,61,61,None,None,CONFLICT,The stories describe materially incompatible p...,"{\n ""reason"": ""The stories describe materiall...",0.724941
18,18,62,62,None,None,CONFLICT,Story A defines an authorization for Admins to...,"{\n ""reason"": ""Story A defines an authorizati...",1.090350
19,19,58,58,None,None,CONFLICT,Story A provides an owner the capability to vi...,"{\n ""reason"": ""Story A provides an owner the ...",0.914577
20,20,10,10,None,None,CONFLICT,"Story A grants a capability to the Publisher, ...","{\n ""reason"": ""Story A grants a capability to...",0.658346
21,21,1,1,None,None,CONFLICT,Story A defines a capability for Publishers to...,"{\n ""reason"": ""Story A defines a capability f...",0.748291
22,22,20,20,None,None,CONFLICT,Story A seeks the ability to preview data pack...,"{\n ""reason"": ""Story A seeks the ability to p...",0.897704
23,23,18,18,None,None,CONFLICT,The stories are materially incompatible becaus...,"{\n ""reason"": ""The stories are materially inc...",0.851870
24,24,17,17,None,None,CONFLICT,Story A defines a functional requirement for P...,"{\n ""reason"": ""Story A defines a functional r...",1.079347
25,25,11,11,None,None,CONFLICT,Story A defines a capability for Publishers to...,"{\n ""reason"": ""Story A defines a capability f...",1.014594
26,26,9,9,None,None,CONFLICT,Story A defines a capability for a Publisher t...,"{\n ""reason"": ""Story A defines a capability f...",0.660349
27,27,48,48,None,None,CONFLICT,Story A defines a notification capability for ...,"{\n ""reason"": ""Story A defines a notification...",0.780883
28,28,8,8,None,None,CONFLICT,Story A defines a capability for Publishers to...,"{\n ""reason"": ""Story A defines a capability f...",0.842713
29,29,3,3,None,None,CONFLICT,The stories provide mutually exclusive signup ...,"{\n ""reason"": ""The stories provide mutually e...",0.747867
30,30,4,4,None,None,CONFLICT,The stories describe fundamentally different s...,"{\n ""reason"": ""The stories describe fundament...",0.855649
31,31,5,5,None,None,DUPLICATE,Both stories describe the same action performe...,"{\n ""reason"": ""Both stories describe the same...",1.032801
32,32,25,25,None,None,CONFLICT,Story A and Story B describe fundamentally con...,"{\n ""reason"": ""Story A and Story B describe f...",0.889359
33,33,26,26,None,None,CONFLICT,Story A and Story B define mutually exclusive ...,"{\n ""reason"": ""Story A and Story B define mut...",0.965645
34,34,30,30,None,None,CONFLICT,Story A and Story B describe diametrically opp...,"{\n ""reason"": ""Story A and Story B describe d...",0.910362
35,35,31,31,None,None,CONFLICT,Story A requires the package to function as a ...,"{\n ""reason"": ""Story A requires the package t...",0.723706
36,36,32,32,None,None,CONFLICT,The stories describe fundamentally different t...,"{\n ""reason"": ""The stories describe fundament...",0.792945
37,37,35,35,None,None,CONFLICT,Story A and Story B describe mutually exclusiv...,"{\n ""reason"": ""Story A and Story B describe m...",0.678473
38,38,36,36,None,None,CONFLICT,Both stories describe the same core action of ...,"{\n ""reason"": ""Both stories describe the same...",1.040417
39,39,37,37,None,None,CONFLICT,Story A requires the system to support multipl...,"{\n ""reason"": ""Story A requires the system to...",0.645474
40,40,38,38,None,None,CONFLICT,Story A requires version pinning for determini...,"{\n ""reason"": ""Story A requires version pinni...",0.724291
41,41,43,43,None,None,CONFLICT,The stories are materially incompatible becaus...,"{\n ""reason"": ""The stories are materially inc...",0.736652
42,42,45,45,None,None,NONE,Both stories involve the same actor (Consumer)...,"{\n ""reason"": ""Both stories involve the same ...",1.023080
43,43,49,49,None,None,CONFLICT,Both stories describe the same user need (asse...,"{\n ""reason"": ""Both stories describe the same...",1.015029
44,44,54,54,None,None,DUPLICATE,Story B adds a conditional constraint (only wh...,"{\n ""reason"": ""Story B adds a conditional con...",0.909592
45,45,56,56,None,None,CONFLICT,Story A and Story B describe the same action o...,"{\n ""reason"": ""Story A and Story B describe t...",0.732187
46,46,61,61,None,None,DUPLICATE,Both stories describe the same Admin role perf...,"{\n ""reason"": ""Both stories describe the same...",0.910429
47,47,62,62,None,None,CONFLICT,Story A requires the system to display specifi...,"{\n ""reason"": ""Story A requires the system to...",1.059143
48,48,52,52,None,None,CONFLICT,Story A and Story B describe diametrically opp...,"{\n ""reason"": ""Story A and Story B describe d...",0.845376
49,49,39,39,None,None,CONFLICT,The stories describe materially incompatible c...,"{\n ""reason"": ""The stories describe materiall...",0.787245
50,50,2,2,None,None,DEPENDS_ON,Story B logically assumes that the capability ...,"{\n ""reason"": ""Story B logically assumes that...",1.106150
51,51,65,65,None,None,DUPLICATE,Both stories describe the same core action of ...,"{\n ""reason"": ""Both stories describe the same...",0.764640
52,52,55,55,None,None,CONFLICT,The stories describe fundamentally different f...,"{\n ""reason"": ""The stories describe fundament...",0.873986
53,53,16,16,None,None,CONFLICT,Story A and Story B represent contradictory de...,"{\n ""reason"": ""Story A and Story B represent ...",1.081317
54,54,63,63,None,None,CONFLICT,The two stories are materially incompatible. S...,"{\n ""reason"": ""The two stories are materially...",0.903661
55,55,19,19,None,None,CONFLICT,The stories describe fundamentally different t...,"{\n ""reason"": ""The stories describe fundament...",0.845637
56,56,22,22,None,None,NONE,The stories describe fundamentally different f...,"{\n ""reason"": ""The stories describe fundament...",0.919191
57,57,0,0,None,None,CONFLICT,The two stories represent contradictory states...,"{\n ""reason"": ""The two stories represent cont...",0.658093

### Exploring the final dataset

In [287]:
import pandas as pd
dff = pd.read_csv(f'pred_res\g14-datahub_FINAL_PROMPT.csv')
dff

<>:2: SyntaxWarning: invalid escape sequence '\g'
<>:2: SyntaxWarning: invalid escape sequence '\g'
C:\Users\havagyan\AppData\Local\Temp\ipykernel_18968\1469134517.py:2: SyntaxWarning: invalid escape sequence '\g'
  dff = pd.read_csv(f'pred_res\g14-datahub_FINAL_PROMPT.csv')

,pair_id_1,pair_id_2,story_1_text,story_2_text,candidate_source,score,predicted_relation,llm_reason,raw_response,response_time_sec
0,0,1,"As a Publisher, I want to publish a dataset, s...","As a Publisher, I want to publish a dataset, s...",cosine,0.900064,CONFLICT,Story A specifies publishing a dataset for a l...,"{\n ""relation_type"": ""CONFLICT"",\n ""source_s...",1.066698
1,0,7,"As a Publisher, I want to publish a dataset, s...","As a Publisher, I want to configure my client,...",cosine,0.620692,NONE,Story A describes the intent to restrict visib...,"{\n ""relation_type"": ""NONE"",\n ""source_story...",1.220146
2,0,16,"As a Publisher, I want to publish a dataset, s...","As a Publisher, I want to publish a data packa...",cosine,0.689316,NONE,Story A focuses on restricting access to a dat...,"{\n ""relation_type"": ""NONE"",\n ""source_story...",1.128119
3,0,17,"As a Publisher, I want to publish a dataset, s...","As a Publisher, I want to create a data packag...",cosine,0.651922,NONE,Story A describes restricting dataset visibili...,"{\n ""relation_type"": ""NONE"",\n ""source_story...",0.895258
4,0,21,"As a Publisher, I want to publish a dataset, s...","As a Consumer, I want to view a data package o...",bm25_enhanced,21.323694,NONE,The stories involve different user roles (Publ...,"{\n ""relation_type"": ""NONE"",\n ""source_story...",1.158858
...,...,...,...,...,...,...,...,...,...,...
349,61,62,"As an Admin, I want to set key configuration p...","As an Admin, I want to see key metrics about u...","bm25_enhanced, cosine",17.204144,NONE,Story A focuses on administrative configuratio...,"{\n ""relation_type"": ""NONE"",\n ""source_story...",1.351542
350,62,63,"As an Admin, I want to see key metrics about u...","As an Admin, I want to have a pricing plan and...","bm25_enhanced, cosine",16.570193,NONE,Story A focuses on administrative analytics an...,"{\n ""relation_type"": ""NONE"",\n ""source_story...",2.060128
351,63,64,"As an Admin, I want to have a pricing plan and...","As a Publisher, I want to know if this site ha...",cosine,0.527958,NONE,Story A focuses on the implementation of a bil...,"{\n ""relation_type"": ""NONE"",\n ""source_story...",1.347895
352,63,65,"As an Admin, I want to have a pricing plan and...","As a Publisher, I want to sign up for a given ...",cosine,0.618391,DEPENDS_ON,Story B depends on the pricing plan and billin...,"{\n ""relation_type"": ""DEPENDS_ON"",\n ""source...",1.144083
353,64,65,"As a Publisher, I want to know if this site ha...","As a Publisher, I want to sign up for a given ...",cosine,0.658487,DEPENDS_ON,Story B depends on Story A because a user must...,"{\n ""relation_type"": ""DEPENDS_ON"",\n ""source...",1.378263

In [297]:

tmp = pd.concat([
    dff[["pair_id_1", "predicted_relation"]]
        .rename(columns={"pair_id_1": "pair_id"}),
    
    dff[["pair_id_2", "predicted_relation"]]
        .rename(columns={"pair_id_2": "pair_id"})
], ignore_index=True)

final_list = (
    tmp.groupby("pair_id")["predicted_relation"]
       .apply(lambda s: s.eq("NONE").all())
)

final_list = final_list[final_list].index.tolist()

print(sorted(final_list))
print(len(sorted(final_list)))
# [3, 4, 5, 6, 8, 9, 13, 22, 25, 26, 30, 31, 32, 33, 34, 35, 37, 38, 43, 45, 46, 48, 49, 54, 57, 60, 61, 62]

[3, 4, 5, 6, 8, 9, 13, 22, 25, 26, 30, 31, 32, 33, 34, 35, 37, 38, 43, 45, 46, 48, 49, 54, 57, 60, 61, 62]
28

In [309]:
ids = final_list

mask_1 = dff["pair_id_1"].isin(ids)
mask_2 = dff["pair_id_2"].isin(ids)

stories_1 = dff.loc[mask_1, ["pair_id_1", "story_1_text"]].rename(
    columns={"pair_id_1": "pair_id", "story_1_text": "story_text"}
)

stories_2 = dff.loc[mask_2, ["pair_id_2", "story_2_text"]].rename(
    columns={"pair_id_2": "pair_id", "story_2_text": "story_text"}
)

stories = (
    pd.concat([stories_1, stories_2], ignore_index=True)
    .drop_duplicates()
    .sort_values("pair_id")
)

stories['story_text'].tolist()

["As a Visitor, I want to sign up via github or google, so that that I don't have to enter lots of information and remember my password for yet another website.",
 'As a Publisher, I want to know what do next after signing up, so that that I can get going quickly.',
 'As an Admin, I want to invite someone to join the platform, so that that they can start contributing or using data.',
 'As a Publisher, I want to import my data package into the registry, so that my data has a permanent online home to access.',
 'As a Publisher, I want to use a publish command to update a data package that is already in the registry, so that it appears there.',
 'As a Publisher, I want to unpublish a data package, so that it is no longer visible to anyone.',
 "As a Consumer, I want to know that the data I am downloading is good and can be relied on, so that that I don't have to check it myself or run into annoying bugs later on.",
 "As a publisher, I want to show the world how my published data is, so that that it immediately catches consumer's attention.",
 'As a Consumer, I want to see how much the data has been downloaded, so that that I can choose most popular in the case when there are several alternatives for my use case.',
 'As a Publisher, I want to see real examples of published packages so that I can understand how useful and simple the datapackage format and the registry is.',
 "As a Consumer, I want to download the data package in one file, so that that I don't have to download descriptor and each resource by hand.",
 'As a Developer, I want to use data package as a node lib in my project, so that that I can depend on it using my normal dependency framework.',
 'As a Consumer, I want to load a Data Package from R, so that that I can immediately start playing with it.',
 'As a Data Analyst I want to download a data package, so that that I can study it and wrangle with it to infer new data or generate new insights.',
 'As a Data Analyst, I want to update previously downloaded data package, so that that I can work with the most recent data.',
 "As a Consumer, I want to download a DataPackage's data one coherent SQLite database, so that that I can get it easily in one form.",
 'As a Web Developer, I want to be able to install multiple versions of the same datapackage separately, so that that all my projects could be developed independently and deployed locally.',
 "As a Developer, I want to list all DataPackages requirements for my project in the file and pin the exact versions of any DataPackage that my project depends on, so that that the project can be deterministically deployed locally and won't break because of the DataPackage schema changes.",
 'As a Publisher, I want to be able to get access to a previous version I tagged, so that that I can return to it and review it.',
 'As a Consumer, I want to get a sense of the age of the datapackage that I have downloaded before, so that that I can decide if I should update or not.',
 'As a Consumer, I want to view a Datapackage at a particular version online, so that that I can present/discuss the particular data timeslice of interest with other people.',
 'As a Consumer, I want to be notified of changes to a package I care about, so that that I can check out what has changed and take action.',
 'As a Consumer, I want to see how active the site is, so that I can decide if I should get involved.',
 'As an Owner, I want to edit my profile, so that that it is updated with new information.',
 'As an owner, I want to remove someone from membership in my publisher, so that they no longer have ability to publish or modify my data packages.',
 'As an owner, I want to remove a user as an owner, so that they are just a member and no longer have full control.',
 'As an Admin, I want to set key configuration parameters for my site deployment, so that that I can change key information like the site title.',
 'As an Admin, I want to see key metrics about usage such as users, API usage, downloads, so that that I know how things are going.']